# Generated by Django 2.1.3 on 2021-05-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawlstarsapp', '0002_auto_20210523_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbattle',
            name='group_players',
        ),
        migrations.RemoveField(
            model_name='onlybattle',
            name='only_players',
        ),
        migrations.AddField(
            model_name='groupbattle',
            name='players',
            field=models.ManyToManyField(through='brawlstarsapp.PlayerGroupBattle', to='brawlstarsapp.Player'),
        ),
        migrations.AddField(
            model_name='onlybattle',
            name='players',
            field=models.ManyToManyField(through='brawlstarsapp.PlayerOnlyBattle', to='brawlstarsapp.Player'),
        ),
    ]
