# Generated by Django 2.1.3 on 2021-05-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brawlstarsapp', '0007_auto_20210523_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergroupbattle',
            name='groupBattle',
        ),
    ]
