# Generated by Django 3.2.2 on 2021-05-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawlstarsapp', '0016_auto_20210523_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergroupbattle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='playeronlybattle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
