# Generated by Django 3.2.2 on 2021-05-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawlstarsapp', '0017_auto_20210523_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
