# Generated by Django 2.1.3 on 2021-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawlstarsapp', '0021_auto_20210523_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbattle',
            name='map',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='onlybattle',
            name='map',
            field=models.CharField(max_length=20),
        ),
    ]
