# Generated by Django 3.2.2 on 2021-05-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brawlstarsapp', '0029_auto_20210526_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbattle',
            name='trophyChange',
        ),
    ]
