# Generated by Django 3.2.2 on 2021-05-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawlstarsapp', '0030_remove_groupbattle_trophychange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbattle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='onlybattle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
