# Generated by Django 3.2.2 on 2021-05-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brawlstarsapp', '0032_auto_20210528_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbattle',
            name='mvp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brawlstarsapp.player'),
        ),
    ]
