# Generated by Django 3.2.2 on 2021-06-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brawlstarsapp', '0033_alter_groupbattle_mvp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupbattle',
            options={'ordering': ('-dateTime',)},
        ),
        migrations.AlterModelOptions(
            name='onlybattle',
            options={'ordering': ('-dateTime',)},
        ),
    ]
