# Generated by Django 3.2.2 on 2021-06-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brawlstarsapp', '0034_auto_20210613_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupbattle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='onlybattle',
            options={},
        ),
    ]
